Diary/config/routes.rb
Rails.application.routes.draw do
  resources :diaries
  match 'diaries/search', via: [:get, :post]

  
  
 

end

Diary/app/models/diary.rb
# coding: utf-8
class Diary < ActiveRecord::Base

  #my change point
  validates_presence_of :title #title not null

  validate :date_isvalid? #check diary date

  private
  def date_isvalid?
    if date < (DateTime.now -1)
      errors.add(:date, '1日以上前の日記を作成・修正することはできません。')
    end
  end
  # end my change point  
end

#test 

Diary/app/models/image.rb
class Image < ActiveRecord::Base
end

Diary/app/models/user.rb
class User < ActiveRecord::Base
end

Diary/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Diary/app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
  before_action :set_diary, only: [:show, :edit, :update, :destroy]
  before_filter :auth, :only => ['new','edit','create','destroy']
  # GET /diaries
  # GET /diaries.json
  def index
    @diaries = Diary.all
    #my
    #@test_form= TestForm.new params[:search_cond]
    #@test = @diaries.search
    #my
  end

  # GET /diaries/1
  # GET /diaries/1.json
  def show
  end

  # GET /diaries/new
  def new
    @diary = Diary.new
  end

  # GET /diaries/1/edit
  def edit
  end

  # POST /diaries
  # POST /diaries.json
  def create
    @diary = Diary.new(diary_params)

    respond_to do |format|
      if @diary.save
        format.html { redirect_to @diary, notice: 'Diary was successfully created.' }
        format.json { render :show, status: :created, location: @diary }
      else
        format.html { render :new }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diaries/1
  # PATCH/PUT /diaries/1.json
  def update
    respond_to do |format|
      if @diary.update(diary_params)
        format.html { redirect_to @diary, notice: 'Diary was successfully updated.' }
        format.json { render :show, status: :ok, location: @diary }
      else
        format.html { render :edit }
        format.json { render json: @diary.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diaries/1
  # DELETE /diaries/1.json
  def destroy
    @diary.destroy
    respond_to do |format|
      format.html { redirect_to diaries_url, notice: 'Diary was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  

  #my change point
 

  
  def search
       @cond =params[:search_cond]
       @diaries= Diary.where('body like ? or title like? or date like?','%' + @cond + '%','%' + @cond + '%','%' + @cond + '%')
        respond_to do |format|
        format.html
        format.json { render json: @diaries}
      
        end
end         
   


  
             


  
  # end my change point search
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diary
      @diary = Diary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diary_params
      params.require(:diary).permit(:date, :title, :body)
    end
end

private

=begin
def auth
  authenticate_or_request_with_http_digest('MyDiary') do |name|
    u = User.find_by_name(name)
    if u
      u.password
    else
      nil
    end
  end
end
=end

#my change code
def auth                                                                                                                                                                                                     realm ='MyDiary'
  authenticate_or_request_with_http_digest(realm) do |name|
    pass = nil
    open('./ht-digest-password'){|io|
      while line = io.gets
        nrp = line.chomp.split(":",3)
        if nrp[1] != realm
          next
        elsif nrp[0] == name
          pass = nrp[2]
          break
        end                                                                                    
      end                                                                                                                                                                                                         }
    pass
    end                                                                                                                                                                                                     
  end                                                                                                                                                                                                       
#end my change code

Diary/app/controllers/images_controller.rb
# coding: utf-8
class ImagesController < ApplicationController


end

Diary/app/helpers/application_helper.rb
module ApplicationHelper
end

Diary/app/helpers/diaries_helper.rb
module DiariesHelper
end

Diary/app/helpers/images_helper.rb
module ImagesHelper
end

Diary/app/views/diaries/_form.html.erb
<%= form_for(@diary) do |f| %>
  <% if @diary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diary.errors.count, "error") %> prohibited this diary from being saved:</h2>

      <ul>
      <% @diary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date, :use_month_number => true %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Diary/app/views/diaries/edit.html.erb
<h1>Editing Diary</h1>

<%= render 'form' %>

<%= link_to 'Show', @diary %> |
<%= link_to 'Back', diaries_path %>

Diary/app/views/diaries/index.html.erb
<p id="notice"><%= notice %></p>

<h1><FONT color=blueviolet>Buku harian saya</FONT></h1>
<body>Buku harian missy s1513127</body>
 
<%=form_tag({:controller => "diaries", :action => "search"}) do %>
検索条件: <%= text_field_tag "search_cond" %>
<%= submit_tag "検索"%>
<% end %>
</tr>



<table border="1" color="blueviolet">
  <thead>
    <tr>
      <th><FONT color=deepskyblue>Date</FONT></th>
      <th><FONT color=deepskyblue>Title</FONT></th>
      <th><FONT color=deepskyblue>Body</FONT></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diaries.each do |diary| %> 
      <tr>
        <td><FONT color=gold><%= diary.date.strftime("%Y年%H時%M分%S秒") %></FONT></td>
        <td><FONT color=gold><%= diary.title %></FONT></td>
        <td><FONT color=gold><%= diary.body %></FONT></td>
        <td><%= link_to 'Show', diary %></td>
        <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
        <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

Diary/app/views/diaries/new.html.erb
<h1>New Diary</h1>
<%= render 'form' %>
<%= link_to 'Back' , diaries_path %>

Diary/app/views/diaries/search.html.erb
<!--my write new -->
<p id="notice"><%= notice %></p>

<h1><FONT color=blueviolet>Found Diaries includes "<%= @cond-%>"</FONT></h1>

<%=form_tag ({:controller =>"diaries", :action => "search"}) do %>
検索条件: <%= text_field_tag "search_cond" %>
<%= submit_tag "検索"%>
<% end %>
</hr>


<table border="1" color="blueviolet">
  <thead>
    <tr>
      <th><FONT color=deepskyblue>Date</FONT></th>
      <th><FONT color=deepskyblue>Title</FONT></th>
      <th><FONT color=deepskyblue>Body</FONT></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @diaries.each do |diary| %>  
    <tr>
      <td><FONT color=gold><%= diary.date.strftime("%Y年%H時%M分%S秒") %></FONT></td>
      <td><FONT color=gold><%= diary.title %></FONT></td>
      <td><FONT color=gold><%= diary.body %></FONT></td>
      <td><%= link_to 'Show', diary %></td>
      <td><%= link_to 'Edit', edit_diary_path(diary) %></td>
      <td><%= link_to 'Destroy', diary, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diary', new_diary_path %>

<%= link_to 'Back', diaries_path %>

Diary/app/views/diaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @diary.date.strftime("%Y年%m月%d日%H時%M分%S秒(%Z)") %>
</p>

<p>
  <strong>Title:</strong>
  <%= @diary.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @diary.body %>
</p>

<%= link_to 'Edit', edit_diary_path(@diary) %> |
<%= link_to 'Back', diaries_path %>

Diary/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <!--add-->
  <head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
      $(function() {
      escapeTag = function(string) {
      if (string == null) return string;
                          return string.replace(/[&<>"']/g,
                     
                        function(match) {
                            return {
                                '&' : '&amp;',
                                '<' : '&lt;',
                                '>' : '&gt;',
          '"' : '&quot;',
	  "'" : '#&39;'
	  }[match];
	  });
	  };

	  var city = '130010'; // Tokyo
	  city = '080020';    // Tsuchiura
	  var wetherURL = 'http://weather.livedoor.com/forecast/webservice/json/v1?city='+city;
	  $.getJSON('http://pipes.yahoo.com/pipes/pipe.run?u='+encodeURI(wetherURL)+'&_id=332d9216d8910ba39e6c2577fd321a6a&_render=json&_callback=?',
	  {},
	  function(json) {
	  var item = json.value.items[0];
	  $('<div><b>'

	      + escapeTag(item.location.city)
	      + escapeTag(item.forecasts[0].dateLabel)
	      + escapeTag(item.forecasts[0].telop)
	      + '</b>'
	    + ' <small>'
	      + escapeTag(item.forecasts[1].dateLabel)
	      + escapeTag(item.forecasts[1].telop)
	      + '</small> <small>copyright livedoor 天気情報</small>'
	                            + '</div>'

	  ).appendTo('#report');
	  });
	  });
	          </script>
    
<title>MyDiary</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>


</head>
<body>

<%= yield %>
<div id="report">
  </div>
</body>
</html>